spring:
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    listener:
      simple:
        #最小消费者数量
        concurrency: 10
        #最大消费者数量
        max-concurrency: 20
        #限制消费者每次只能处理一条消息
        prefetch: 1
        #启动时默认启动mq
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #重试
        enabled: true
        #访问等待时间
        initial-interval: 1000ms
        # 最大重试次数
        max-attempts: 3
        #最大重试时间间隔
        max-interval: 10000ms
        #重试最大间隔乘数 比如给2 则第一次等待10S 第二次等待20S 第三次等待40S
        multiplier: 1
  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    #模板
#    enabled: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
    #默认数据库
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: 10000ms
        #最大空闲连接数
        max-idle: 200
        min-idle: 0
# Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.bytedance.pojo
## Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.itheida.mapper: debug